"""
demo.py -- Command-line demo for the Multi-Agent Research System.

Runs the full five-agent pipeline against a hard-coded topic and prints
each agent's output to stdout. No Streamlit is required; the demo only
needs GROQ_API_KEY to be set (in the environment or in a .env file).

Usage:
    python demo.py
    python demo.py "Your custom research topic here"
"""

import os
import re
import sys
import textwrap
from datetime import datetime

from dotenv import load_dotenv

load_dotenv()


# ---------------------------------------------------------------------------
# Agent definitions (mirrors app.py)
# ---------------------------------------------------------------------------

AGENTS = [
    {
        "id": "planner",
        "name": "Planner",
        "role": "Breaks topic into structured research questions",
        "prompt": (
            "You are a Research Planner AI. Analyse this topic and create a structured research plan.\n\n"
            "Topic: {topic}\n\n"
            "Output EXACTLY:\n"
            "RESEARCH PLAN:\n"
            "1. [Specific research question]\n"
            "2. [Specific research question]\n"
            "3. [Specific research question]\n"
            "4. [Specific research question]\n"
            "5. [Specific research question]\n\n"
            "KEY FOCUS AREAS:\n"
            "- [Area 1]\n"
            "- [Area 2]\n"
            "- [Area 3]\n\n"
            "RESEARCH APPROACH:\n"
            "[2-3 sentences on how to investigate this topic effectively]"
        ),
    },
    {
        "id": "researcher",
        "name": "Researcher",
        "role": "Investigates each question with detailed findings",
        "prompt": (
            "You are a Domain Researcher AI. Investigate each question from the research plan thoroughly.\n\n"
            "Topic: {topic}\n"
            "Research Plan: {planner}\n\n"
            "For each research question provide detailed findings. Format as:\n\n"
            "RESEARCH FINDINGS:\n\n"
            "Q1: [question]\n"
            "Findings: [detailed findings with facts, context, examples]\n\n"
            "Q2: [question]\n"
            "Findings: [detailed findings]\n\n"
            "Q3: [question]\n"
            "Findings: [detailed findings]\n\n"
            "Q4: [question]\n"
            "Findings: [detailed findings]\n\n"
            "Q5: [question]\n"
            "Findings: [detailed findings]"
        ),
    },
    {
        "id": "analyst",
        "name": "Analyst",
        "role": "Identifies patterns, trends and insights",
        "prompt": (
            "You are a Data Analyst AI. Analyse all research findings and extract key insights.\n\n"
            "Topic: {topic}\n"
            "Research Findings: {researcher}\n\n"
            "Provide:\n"
            "ANALYSIS REPORT:\n\n"
            "KEY PATTERNS IDENTIFIED:\n"
            "- [Pattern 1 with evidence]\n"
            "- [Pattern 2 with evidence]\n"
            "- [Pattern 3 with evidence]\n"
            "- [Pattern 4 with evidence]\n\n"
            "CRITICAL INSIGHTS:\n"
            "1. [Insight + why it matters]\n"
            "2. [Insight + why it matters]\n"
            "3. [Insight + why it matters]\n\n"
            "TREND ANALYSIS:\n"
            "[2-3 sentences on trends]\n\n"
            "CONTRADICTIONS OR GAPS:\n"
            "- [Any conflicting information or missing data]\n\n"
            "CONFIDENCE ASSESSMENT: [High/Medium/Low] -- [reason]"
        ),
    },
    {
        "id": "writer",
        "name": "Writer",
        "role": "Synthesises everything into a polished report",
        "prompt": (
            "You are a Professional Report Writer AI. Create a comprehensive research report.\n\n"
            "Topic: {topic}\n"
            "Research Plan: {planner}\n"
            "Findings: {researcher}\n"
            "Analysis: {analyst}\n\n"
            "Write a complete professional report:\n\n"
            "# {topic}\n\n"
            "## Executive Summary\n"
            "[3-4 sentence overview of the most important conclusions]\n\n"
            "## Background and Context\n"
            "[Why this topic matters, current landscape]\n\n"
            "## Key Findings\n"
            "[5-6 major findings with supporting evidence, use bullet points]\n\n"
            "## In-Depth Analysis\n"
            "[3-4 paragraphs analysing the findings and their implications]\n\n"
            "## Implications and Applications\n"
            "[What this means in practice, who should care and why]\n\n"
            "## Conclusion\n"
            "[Clear, actionable conclusions -- what does this all mean?]\n\n"
            "---\n"
            "*Report generated by Multi-Agent Research System*"
        ),
    },
    {
        "id": "critic",
        "name": "Critic",
        "role": "Reviews quality and scores the report",
        "prompt": (
            "You are a Quality Control AI. Rigorously review this research report.\n\n"
            "Report: {writer}\n"
            "Original Topic: {topic}\n\n"
            "Evaluate critically on 5 dimensions:\n\n"
            "QUALITY REVIEW:\n\n"
            "DIMENSION SCORES (each out of 10):\n"
            "- Completeness: [X/10] -- [brief reason]\n"
            "- Accuracy & Evidence: [X/10] -- [brief reason]\n"
            "- Clarity & Writing: [X/10] -- [brief reason]\n"
            "- Structure & Flow: [X/10] -- [brief reason]\n"
            "- Analytical Depth: [X/10] -- [brief reason]\n\n"
            "OVERALL SCORE: [X/10]\n\n"
            "STRENGTHS:\n"
            "- [Specific strength]\n"
            "- [Specific strength]\n"
            "- [Specific strength]\n\n"
            "WEAKNESSES:\n"
            "- [Specific weakness]\n"
            "- [Specific weakness]\n\n"
            "MISSING ELEMENTS:\n"
            "- [What could have been included]\n\n"
            "VERDICT: [Approved for Publication / Needs Revision] -- [one sentence reason]"
        ),
    },
]

AGENT_INPUTS: dict[str, list[str]] = {
    "planner": [],
    "researcher": ["planner"],
    "analyst": ["researcher"],
    "writer": ["planner", "researcher", "analyst"],
    "critic": ["writer"],
}

DEFAULT_TOPIC = "The current state and future potential of retrieval-augmented generation (RAG) in enterprise AI"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def separator(char: str = "-", width: int = 72) -> str:
    return char * width


def print_header(text: str) -> None:
    print("\n" + separator("="))
    print(f"  {text}")
    print(separator("="))


def print_agent_header(agent: dict) -> None:
    print("\n" + separator("-"))
    print(f"  Agent: {agent['name']}  |  {agent['role']}")
    print(separator("-"))


def wrap_output(text: str, width: int = 72, indent: str = "  ") -> str:
    lines = []
    for para in text.splitlines():
        if para.strip() == "":
            lines.append("")
        else:
            wrapped = textwrap.fill(para, width=width - len(indent))
            lines.extend((indent + line) for line in wrapped.splitlines())
    return "\n".join(lines)


def extract_score(critic_text: str) -> int:
    match = re.search(r"OVERALL\s+SCORE\s*:\s*(\d+)\s*/\s*10", critic_text, re.IGNORECASE)
    if match:
        return max(1, min(10, int(match.group(1))))
    for line in critic_text.splitlines():
        if "OVERALL SCORE" in line.upper():
            numbers = re.findall(r"\b(\d{1,2})\b", line)
            for n in numbers:
                val = int(n)
                if 1 <= val <= 10:
                    return val
    return 7


def run_agent(agent: dict, inputs: dict, llm) -> str:
    try:
        prompt = agent["prompt"].format(**inputs)
    except KeyError as exc:
        raise ValueError(f"Agent '{agent['id']}' prompt missing variable: {exc}") from exc

    try:
        response = llm.invoke(prompt)
        return response.content.strip()
    except Exception as exc:
        raise RuntimeError(f"Agent '{agent['id']}' LLM call failed: {exc}") from exc


def save_report(topic: str, report: str, score: int) -> str:
    """Save the final report to a timestamped file and return the path."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_topic = re.sub(r"[^\w\s-]", "", topic)[:40].strip().replace(" ", "_")
    filename = f"report_{safe_topic}_{timestamp}.md"

    header = (
        f"# Research Report\n\n"
        f"**Topic:** {topic}\n"
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"**Quality Score:** {score}/10\n"
        f"**System:** Multi-Agent Research System\n\n"
        f"---\n\n"
    )

    with open(filename, "w", encoding="utf-8") as f:
        f.write(header + report)

    return filename


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    topic = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TOPIC

    api_key = os.getenv("GROQ_API_KEY", "").strip()
    if not api_key:
        print(
            "ERROR: GROQ_API_KEY is not set.\n"
            "Set it in your environment or in a .env file:\n"
            "  GROQ_API_KEY=gsk_...\n"
            "Get a free key at https://console.groq.com"
        )
        sys.exit(1)

    # Import here so the module can be imported without langchain installed
    try:
        from langchain_groq import ChatGroq
    except ImportError:
        print("ERROR: langchain-groq is not installed. Run: pip install langchain-groq")
        sys.exit(1)

    llm = ChatGroq(
        model_name="llama3-8b-8192",
        temperature=0.4,
        groq_api_key=api_key,
        max_tokens=2000,
    )

    print_header(f"Multi-Agent Research System -- Demo Run")
    print(f"\n  Topic : {topic}")
    print(f"  Model : llama3-8b-8192 via Groq")
    print(f"  Agents: {len(AGENTS)}")
    print(f"  Time  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    outputs: dict[str, str] = {}
    inputs: dict[str, str] = {"topic": topic}

    for agent in AGENTS:
        print_agent_header(agent)
        print(f"  Running...")

        # Inject prior outputs
        for dep in AGENT_INPUTS.get(agent["id"], []):
            inputs[dep] = outputs.get(dep, "")

        try:
            output = run_agent(agent, inputs, llm)
        except (ValueError, RuntimeError) as exc:
            print(f"\n  FAILED: {exc}")
            print("\n  Pipeline aborted.")
            sys.exit(1)

        outputs[agent["id"]] = output

        # Print a trimmed preview (first 800 chars)
        preview = output[:800]
        if len(output) > 800:
            preview += "\n  [... truncated for display ...]"
        print(f"\n{wrap_output(preview)}")

    # Results summary
    final_report = outputs.get("writer", "")
    critic_output = outputs.get("critic", "")
    score = extract_score(critic_output)
    word_count = len(final_report.split())

    print_header("Pipeline Complete")
    print(f"\n  Quality Score : {score}/10")
    print(f"  Word Count    : {word_count:,} words in final report")
    print(f"  Agents Run    : {len(AGENTS)}")

    saved_path = save_report(topic, final_report, score)
    print(f"\n  Report saved to: {saved_path}")
    print(f"\n  To view the full report, open the saved file.")
    print(separator("=") + "\n")


if __name__ == "__main__":
    main()
